name: sign3
type: 'php:8.0'

web:
  locations:
    '/':
      root: 'public'  # Make sure the root points to the 'public' directory
      index: 'index.php'  # The entry point is index.php in the 'public' directory
      passthru: '/index.php'
      allow: all
