name: sign3
type: 'php:8.0'

web:
  locations:
    '/':
      root: 'public'  # Set the root to the public folder
      index: 'index.php'  # Use index.php from the public folder
      passthru: '/index.php'
      allow: all

# Optional: If you have a database
services:
  database: 'mysql:10.3'

# If you need to include any build steps
build:
  flavor: 'php'
