name: sign3
type: 'php:8.0'

web:
  locations:
    '/':
      root: 'public'  # Make sure the root points to the 'public' directory
      index:
        - 'index.php'  # Define index as an array with 'index.php'
      passthru: '/index.php'
      allow: all
